"use client";

import { useState } from "react";
import { PrimaryButton } from "@/components/ui/action-button";
import type { TeamMember } from "@/lib/team";
import { normalizeSongIds } from "@/lib/service-item-normalization";
import { parseAssignmentText } from "@/lib/assignment-text";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

const inputStyles = "min-h-12 w-full rounded-2xl border border-white/10 bg-zinc-950/60 px-4 text-white outline-none focus:border-emerald-400/50";
const actionStyles = "min-h-11 rounded-xl px-3 text-sm font-semibold text-zinc-400 hover:bg-white/[0.05] hover:text-white disabled:opacity-40";
const nameCollator = new Intl.Collator("es", { sensitivity: "base" });

export function ManageTeam({ initialMembers }: { initialMembers: TeamMember[] }) {
  const [members, setMembers] = useState(initialMembers); const [editing, setEditing] = useState<TeamMember | null>(null); const [showForm, setShowForm] = useState(false); const [name, setName] = useState(""); const [busyId, setBusyId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [isError, setIsError] = useState(false);
  function openForm(member?: TeamMember) { setEditing(member ?? null); setName(member?.name ?? ""); setShowForm(true); setMessage(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || busyId) return; setBusyId(editing?.id ?? "new"); const supabase = createSupabaseBrowserClient(); const result = editing ? await supabase.from("team_members").update({ name: name.trim() }).eq("id", editing.id).select("id, name, instrument, active, sort_order").single() : await supabase.from("team_members").insert({ name: name.trim(), sort_order: members.length }).select("id, name, instrument, active, sort_order").single(); if (result.error) { setIsError(true); setMessage(result.error.code === "23505" ? "Ya existe una persona con ese nombre." : result.error.message); } else { const saved = result.data as TeamMember; setMembers((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved]); setShowForm(false); setIsError(false); setMessage("Equipo actualizado."); } setBusyId(null); }
  async function setActive(member: TeamMember, active: boolean) { setBusyId(member.id); const supabase = createSupabaseBrowserClient(); const { error } = await supabase.from("team_members").update({ active }).eq("id", member.id); if (!error) setMembers((current) => current.map((item) => item.id === member.id ? { ...item, active } : item)); setBusyId(null); }
  async function remove(member: TeamMember) { setBusyId(member.id); const supabase = createSupabaseBrowserClient(); const [{ data: assignments }, { data: serviceItems }] = await Promise.all([supabase.from("microphone_assignments").select("leader_name"), supabase.from("service_items").select("details, song_ids")]); const used = (assignments ?? []).some((item) => parseAssignmentText(item.leader_name).name === member.name) || (serviceItems ?? []).some((item) => parseAssignmentText(item.details ?? "").name === member.name || normalizeSongIds(item.song_ids).entries.some((entry) => parseAssignmentText(entry.notes).name === member.name)); if (used) { setIsError(true); setMessage("No se puede eliminar esta persona. Puedes desactivarla."); setBusyId(null); return; } const { error } = await supabase.from("team_members").delete().eq("id", member.id); if (error) { setIsError(true); setMessage("No se puede eliminar esta persona. Puedes desactivarla."); } else setMembers((current) => current.filter((item) => item.id !== member.id)); setBusyId(null); }
  const activeMembers = members.filter((member) => member.active).sort((a, b) => nameCollator.compare(a.name, b.name)); const inactiveMembers = members.filter((member) => !member.active).sort((a, b) => nameCollator.compare(a.name, b.name));
  return <div className="mt-6"><PrimaryButton type="button" onClick={() => openForm()}>Agregar persona</PrimaryButton>{showForm ? <form onSubmit={save} className="mt-4 rounded-2xl border border-white/[0.07] p-4"><label className="text-sm font-semibold text-zinc-300">Nombre<input autoFocus required value={name} onChange={(event) => setName(event.target.value)} className={`mt-2 ${inputStyles}`} /></label><div className="mt-3 flex gap-2"><PrimaryButton type="submit" disabled={busyId !== null}>{busyId ? "Guardando..." : "Guardar"}</PrimaryButton><button type="button" onClick={() => setShowForm(false)} className="min-h-12 px-4 text-zinc-400">Cancelar</button></div></form> : null}<MemberList title="Activos" members={activeMembers} busyId={busyId} onEdit={openForm} onToggle={(member) => void setActive(member, false)} onDelete={(member) => void remove(member)} /><MemberList title="Inactivos" members={inactiveMembers} busyId={busyId} onEdit={openForm} onToggle={(member) => void setActive(member, true)} onDelete={(member) => void remove(member)} /><p role="status" className={`mt-4 text-sm ${isError ? "text-rose-300" : "text-emerald-400"}`}>{message}</p></div>;
}

function MemberList({ title, members, busyId, onEdit, onToggle, onDelete }: { title: string; members: TeamMember[]; busyId: string | null; onEdit: (member: TeamMember) => void; onToggle: (member: TeamMember) => void; onDelete: (member: TeamMember) => void }) { return <section className="mt-6"><h2 className="text-lg font-semibold text-white">{title}</h2>{members.length ? <div className="mt-2 divide-y divide-white/[0.07] border-y border-white/[0.07]">{members.map((member) => <div key={member.id} className="flex flex-col gap-3 py-3 sm:flex-row sm:items-center"><p className="min-w-0 flex-1 font-semibold text-white">{member.name}</p><div className="flex flex-wrap gap-1"><button type="button" onClick={() => onEdit(member)} className={actionStyles}>Editar</button><button type="button" onClick={() => onToggle(member)} disabled={busyId !== null} className={actionStyles}>{member.active ? "Desactivar" : "Reactivar"}</button><button type="button" onClick={() => onDelete(member)} disabled={busyId !== null} className={`${actionStyles} text-rose-300`}>Eliminar</button></div></div>)}</div> : <p className="mt-2 py-6 text-sm text-zinc-500">No hay personas en esta sección.</p>}</section>; }
