"use client";

import { useEffect, useState } from "react";
import { isValidMusicalGrid, type MusicalGrid } from "@/lib/musical-grid";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

export function MusicalGridEditor({ getCurrentTime, fallbackBpm, fallbackTimeSignature, grid, onSaved, songKeyId }: { getCurrentTime: () => number; fallbackBpm: number | null; fallbackTimeSignature: string | null; grid: MusicalGrid | null; onSaved: (grid: MusicalGrid) => void; songKeyId: string }) {
  const fallbackMeter = parseMeter(fallbackTimeSignature);
  const [draft, setDraft] = useState(() => ({ bpm: String(grid?.bpm ?? fallbackBpm ?? 120), beatsPerBar: String(grid?.beatsPerBar ?? fallbackMeter.beatsPerBar), beatUnit: String(grid?.beatUnit ?? fallbackMeter.beatUnit), offset: formatGridTime(grid?.gridOffsetSeconds ?? 0) }));
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { setDraft({ bpm: String(grid?.bpm ?? fallbackBpm ?? 120), beatsPerBar: String(grid?.beatsPerBar ?? fallbackMeter.beatsPerBar), beatUnit: String(grid?.beatUnit ?? fallbackMeter.beatUnit), offset: formatGridTime(grid?.gridOffsetSeconds ?? 0) }); }, [fallbackBpm, fallbackMeter.beatUnit, fallbackMeter.beatsPerBar, grid]);
  async function save(event: React.FormEvent) { event.preventDefault(); const next: MusicalGrid = { bpm: Number(draft.bpm), beatsPerBar: Number(draft.beatsPerBar), beatUnit: Number(draft.beatUnit), gridOffsetSeconds: parseGridTime(draft.offset) }; if (!isValidMusicalGrid(next)) { setMessage("Revisa BPM, compás y offset."); return; } setSaving(true); const { error } = await createSupabaseBrowserClient().from("song_keys").update({ grid_bpm: next.bpm, grid_beats_per_bar: next.beatsPerBar, grid_beat_unit: next.beatUnit, grid_offset_seconds: Number(next.gridOffsetSeconds.toFixed(3)) }).eq("id", songKeyId); setSaving(false); if (error) { setMessage(error.message); return; } setMessage("Grid guardado."); onSaved(next); }
  return <form onSubmit={(event) => void save(event)} className="border-y border-white/[0.07] bg-emerald-950/[0.05] px-4 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-400">Grid musical</p><p className="mt-0.5 text-[0.6875rem] text-zinc-600">BPM de negra · configuración por tonalidad</p></div><button type="button" onClick={() => setDraft((value) => ({ ...value, offset: formatGridTime(getCurrentTime()) }))} className="min-h-9 rounded-lg border border-white/10 px-3 text-xs font-semibold text-zinc-300 hover:bg-white/[0.04]">Usar posición actual</button></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><GridField label="BPM" value={draft.bpm} onChange={(bpm) => setDraft({ ...draft, bpm })} /><GridField label="Pulsos" value={draft.beatsPerBar} onChange={(beatsPerBar) => setDraft({ ...draft, beatsPerBar })} /><label className="text-xs font-semibold text-zinc-500">Unidad<select value={draft.beatUnit} onChange={(event) => setDraft({ ...draft, beatUnit: event.target.value })} className="mt-1 min-h-10 w-full rounded-lg border border-white/10 bg-zinc-950 px-2 text-sm text-white"><option value="4">1/4</option><option value="8">1/8</option><option value="2">1/2</option><option value="16">1/16</option></select></label><GridField label="Compás 1 · Beat 1" value={draft.offset} onChange={(offset) => setDraft({ ...draft, offset })} /></div><div className="mt-3 flex items-center justify-between gap-3"><p role="status" className={`text-xs ${message === "Grid guardado." ? "text-emerald-300" : "text-rose-300"}`}>{message}</p><button type="submit" disabled={saving} className="min-h-9 rounded-lg bg-emerald-400 px-3 text-xs font-bold text-zinc-950 disabled:opacity-40">{saving ? "Guardando…" : "Guardar grid"}</button></div></form>;
}

function GridField({ label, onChange, value }: { label: string; onChange: (value: string) => void; value: string }) { return <label className="text-xs font-semibold text-zinc-500">{label}<input value={value} onChange={(event) => onChange(event.target.value)} inputMode="decimal" className="mt-1 min-h-10 w-full rounded-lg border border-white/10 bg-zinc-950 px-2 text-sm text-white outline-none focus:border-emerald-400/50" /></label>; }
function parseMeter(value: string | null) { const match = value?.match(/^(\d+)\/(\d+)$/); return match ? { beatsPerBar: Number(match[1]), beatUnit: Number(match[2]) } : { beatsPerBar: 4, beatUnit: 4 }; }
function formatGridTime(seconds: number) { const milliseconds = Math.round(Math.max(0, seconds) * 1000); return `${Math.floor(milliseconds / 60000)}:${String(Math.floor((milliseconds % 60000) / 1000)).padStart(2, "0")}.${String(milliseconds % 1000).padStart(3, "0")}`; }
function parseGridTime(value: string) { const match = value.trim().match(/^(\d+):(\d{1,2})(?:\.(\d{1,3}))?$/); if (!match || Number(match[2]) >= 60) return Number.NaN; return Number(match[1]) * 60 + Number(match[2]) + Number(`0.${(match[3] ?? "").padEnd(3, "0") || "0"}`); }
