"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { MultitrackPlayer, type PublicSongStem } from "@/components/multitrack-player";
import { loadStemBundle } from "@/lib/audio-buffer-cache";
export type PlaybackEntry = { artist: string | null; bpm: number | null; coverUrl: string | null; durationLabel: string; effectiveKey: string | null; id: string; kind: "moment" | "song"; scheduledTime: string; stems: PublicSongStem[]; timeSignature: string | null; title: string };

export function PlaybackWorkspace({ entries, serviceId, serviceName, serviceSchedule }: { entries: PlaybackEntry[]; serviceId: number; serviceName: string; serviceSchedule: string }) {
  const firstSongIndex = useMemo(() => Math.max(0, entries.findIndex((entry) => entry.kind === "song")), [entries]);
  const [selectedIndex, setSelectedIndex] = useState(firstSongIndex); const selected = entries[selectedIndex] ?? null;
  const songIndexes = useMemo(() => entries.flatMap((entry, index) => entry.kind === "song" ? [index] : []), [entries]); const songPosition = songIndexes.indexOf(selectedIndex);
  function selectAdjacent(direction: -1 | 1) { if (!songIndexes.length) return; const current = songPosition >= 0 ? songPosition : direction > 0 ? -1 : songIndexes.length; setSelectedIndex(songIndexes[Math.min(songIndexes.length - 1, Math.max(0, current + direction))]); }
  useEffect(() => { const Ctor = window.AudioContext ?? (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!Ctor || !selected?.stems.length) return; const context = new Ctor(); let current = true; const nextIndex = songPosition >= 0 ? songIndexes[songPosition + 1] : undefined; const next = nextIndex === undefined ? null : entries[nextIndex]; void loadStemBundle(context, selected.stems, { label: selected.title, mode: "foreground" }).then(() => current && next?.stems.length ? loadStemBundle(context, next.stems, { label: next.title, mode: "preload" }) : null).finally(() => void context.close()); return () => { current = false; }; }, [entries, selected, songIndexes, songPosition]);
  return <div className="min-h-screen lg:grid lg:grid-cols-[270px_minmax(0,1fr)]">
    <aside className="border-b border-white/[0.07] bg-[#07100e]/75 lg:min-h-[calc(100dvh-4rem)] lg:border-b-0 lg:border-r"><div className="px-4 py-3 lg:px-5 lg:pb-4 lg:pt-5"><p className="text-[0.6875rem] font-bold uppercase tracking-[0.18em] text-emerald-400">Playback</p><h1 className="mt-3 truncate text-base font-semibold text-white">{serviceName}</h1><p className="mt-1 truncate text-xs text-zinc-500">{serviceSchedule || "Horario por confirmar"}</p></div><nav className="flex h-11 overflow-x-auto border-y border-white/[0.07] px-4 text-[0.8125rem] font-semibold lg:hidden"><Link href={`/service/${serviceId}`} className={navClass}>Orden</Link><Link href={`/service/${serviceId}/notes`} className={navClass}>Notas</Link><Link href={`/service/${serviceId}/rehearsal`} className={navClass}>Ensayo</Link><span className={`${navClass} border-emerald-400 text-emerald-300`}>Playback</span><Link href={`/service/${serviceId}/report`} className={navClass}>Reporte</Link></nav><div className="hidden border-y border-white/[0.07] px-5 py-2 text-[0.625rem] font-bold uppercase tracking-[0.16em] text-zinc-600 lg:block">Setlist</div><ol className="hidden max-h-[calc(100dvh-12rem)] divide-y divide-white/[0.045] overflow-y-auto lg:block">{entries.map((entry, index) => <li key={entry.id}><button type="button" onClick={() => setSelectedIndex(index)} className={`grid min-h-[3.65rem] w-full grid-cols-[2.75rem_minmax(0,1fr)_auto] items-center gap-2 border-l-2 px-3 py-1.5 text-left ${selectedIndex === index ? "border-emerald-400 bg-emerald-400/[0.11]" : "border-transparent hover:bg-white/[0.03]"}`}><span className={`text-xs tabular-nums ${selectedIndex === index ? "text-emerald-300" : "text-zinc-600"}`}>{entry.scheduledTime}</span><span className="min-w-0"><span className={`block truncate text-[0.8125rem] font-semibold ${entry.kind === "song" ? "text-zinc-200" : "text-zinc-400"}`}>{entry.title}</span><span className="mt-0.5 block text-[0.6875rem] tabular-nums text-zinc-600">{entry.durationLabel}</span></span>{entry.kind === "song" && entry.effectiveKey ? <span className="grid size-7 place-items-center rounded-full border border-emerald-400/30 text-[0.6875rem] font-bold text-emerald-300">{entry.effectiveKey}</span> : null}</button></li>)}</ol></aside>
    <main className="min-w-0 bg-[#090e0d] px-4 pb-20 pt-4 sm:px-6 lg:h-[calc(100dvh-4rem)] lg:overflow-y-auto lg:p-4"><div className="mx-auto max-w-[1680px]">{selected ? <><header className="flex items-center gap-3 border-b border-white/[0.07] pb-4 lg:hidden">{selected.coverUrl ? <Image src={selected.coverUrl} alt="" width={64} height={64} unoptimized className="size-14 rounded-lg object-cover" /> : <div className="grid size-14 place-items-center rounded-lg border border-white/[0.07] text-zinc-700">♪</div>}<div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate text-xl font-bold text-white">{selected.title}</h2>{selected.effectiveKey ? <span className="rounded-md border border-emerald-400/25 px-2 py-1 text-xs font-bold text-emerald-300">{selected.effectiveKey}</span> : null}</div><p className="truncate text-sm text-zinc-400">{selected.artist}</p><p className="mt-1 text-xs text-zinc-500">{[selected.bpm ? `${selected.bpm} BPM` : null, selected.timeSignature].filter(Boolean).join(" · ")}</p></div></header>{selected.kind === "song" ? <section className="py-4 lg:py-0">{selected.stems.length ? <MultitrackPlayer key={selected.id} active artist={selected.artist} artworkUrl={selected.coverUrl} bpm={selected.bpm} canPrevious={songPosition > 0} canNext={songPosition >= 0 && songPosition < songIndexes.length - 1} effectiveKey={selected.effectiveKey} layout="playback" onPrevious={() => selectAdjacent(-1)} onNext={() => selectAdjacent(1)} stems={selected.stems} timeSignature={selected.timeSignature} title={selected.title} showStop /> : <div className="border-y border-white/[0.07] py-8 text-center text-sm text-zinc-500">No hay pistas disponibles para {selected.effectiveKey ? `la tonalidad ${selected.effectiveKey}` : "esta canción"}.</div>}</section> : <p className="py-10 text-center text-sm text-zinc-500">Selecciona una canción del orden para abrir Playback.</p>}</> : <p className="py-12 text-center text-sm text-zinc-500">Este servicio no tiene elementos.</p>}</div></main>
  </div>;
}
const navClass = "flex min-h-11 shrink-0 items-center border-b-2 border-transparent px-2.5 text-zinc-400";
